#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.18
#  in conjunction with Tcl version 8.6
#    Nov 24, 2018 09:36:38 PM EST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

import sys, os.path
datapath = os.path.abspath(os.path.join(os.path.dirname(__file__), "../..") + '/OA Data Files')
import app_config

import GUI_List_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    GUI_List_support.set_Tk_var()
    top = Toplevel1 (root)
    GUI_List_support.init(root, top)
    root.mainloop()

w = None

def create_toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win
    #, rt
    #rt = root

    if root == None:
        w = tk.Tk()
    else:
        w = tk.Toplevel (root)

#    GUI_List_support.set_Tk_var()
    top = Toplevel1 (w)
    GUI_List_support.init(w, top, *args, **kwargs)
    return (w, top)

def build_list(list_type, list_items, editcall, removecall):
    GUI_List_support.build_list(list_type, list_items, editcall, removecall)

def destroy_toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):

        font9 = "-family {Segoe UI} -size 20 -weight bold -slant roman"  \
            " -underline 0 -overstrike 0"

        top.title("LIST NOT LOADED")

        self.f1 = tk.Frame(top)
        self.f1.grid(sticky='nsew', row=2, column=0, padx=20, pady=20)

        self.lbltitle = tk.Label(top, text='LIST NOT LOADED')
        self.lbltitle.configure(font=font9)
        self.lbltitle.grid(sticky='nsew', row=0, column=0, columnspan=3, rowspan=2, pady=20)

        self.cancel = tk.Button(top, text='Cancel', command=GUI_List_support.cancel_click)
        self.cancel.config(width=10, height=2)
        self.cancel.grid(sticky='sw', row=3, column=0, padx=20, pady=20)

        self.cancel = tk.Button(top, text='NEW', command=GUI_List_support.new_click)
        self.cancel.config(width=10, height=2)
        self.cancel.grid(sticky='sw', row=3, column=2, padx=20, pady=20)

        self.f1.grid_columnconfigure(0, weight=1)
        self.f1.grid_columnconfigure(1, weight=3)
        self.f1.grid_columnconfigure(2, weight=1)

if __name__ == '__main__':
    vp_start_gui()
