#############################################################################
# Generated by PAGE version 4.18
#  in conjunction with Tcl version 8.6
#  Nov 25, 2018 01:37:59 PM EST  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
}

#############################################################################
# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {Segoe UI} -size 20 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font9
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 944x1048+-1474+119
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 3844 1061
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "New Toplevel"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    label $top.lab43 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font9,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Archtype - <name>} 
    vTcl:DefineAlias "$top.lab43" "lblTitle" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab44 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Name 
    vTcl:DefineAlias "$top.lab44" "lblName" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab45 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text <name> 
    vTcl:DefineAlias "$top.lab45" "roName" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent47 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent47" "rwName" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab48 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Proficiency 
    vTcl:DefineAlias "$top.lab48" "lblProficiency" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab49 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Label 
    vTcl:DefineAlias "$top.lab49" "roProficiency" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent50 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent50" "rwProficiency" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab51 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Description 
    vTcl:DefineAlias "$top.lab51" "lblDescription" vTcl:WidgetProc "Toplevel1" 1
    text $top.tex52 \
        -background white -font TkTextFont -foreground black -height 154 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 334 -wrap word 
    .top42.tex52 configure -font TkTextFont
    .top42.tex52 insert end text
    vTcl:DefineAlias "$top.tex52" "txtDescription" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab53 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Bonuses 
    vTcl:DefineAlias "$top.lab53" "lblBonuses" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab54 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text STR 
    vTcl:DefineAlias "$top.lab54" "lblSTR" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab55 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Label 
    vTcl:DefineAlias "$top.lab55" "roSTR" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent56 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent56" "rwPER" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab57 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text PER 
    vTcl:DefineAlias "$top.lab57" "lblPER" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab59 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Label 
    vTcl:DefineAlias "$top.lab59" "roPER" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent61 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent61" "rwINT" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab62 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text INT 
    vTcl:DefineAlias "$top.lab62" "lblINT" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab63 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Label 
    vTcl:DefineAlias "$top.lab63" "roINT" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab64 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text DEX 
    vTcl:DefineAlias "$top.lab64" "lblDEX" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab65 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text CHA 
    vTcl:DefineAlias "$top.lab65" "lblCHA" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab66 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text VIT 
    vTcl:DefineAlias "$top.lab66" "lblVIT" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab67 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text MAG 
    vTcl:DefineAlias "$top.lab67" "lblMAG" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent68 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent68" "rwDEX" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent69 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent69" "rwCHA" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent70 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent70" "rwVIT" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent71 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent71" "rwMAG" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent43 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent43" "rwSTR" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab46 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Label 
    vTcl:DefineAlias "$top.lab46" "roPDEX" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab47 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Label 
    vTcl:DefineAlias "$top.lab47" "roCHA" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab50 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Label 
    vTcl:DefineAlias "$top.lab50" "roVIT" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab52 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Label 
    vTcl:DefineAlias "$top.lab52" "roMAG" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab56 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Feats 
    vTcl:DefineAlias "$top.lab56" "lblFeats" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab58 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Mvmt 
    vTcl:DefineAlias "$top.lab58" "lblMvmt" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab60 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {Skill Pts} 
    vTcl:DefineAlias "$top.lab60" "lblSkillPts" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab61 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {Lvl Health} 
    vTcl:DefineAlias "$top.lab61" "lblLvlHealth" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent62 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent62" "rwFeats" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent63 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent63" "rwMvmt" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent64 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent64" "rwSkillPts" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent65 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent65" "rwLvlHealth" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab68 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Label 
    vTcl:DefineAlias "$top.lab68" "roFeats" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab69 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Label 
    vTcl:DefineAlias "$top.lab69" "roMvmt" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab70 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Label 
    vTcl:DefineAlias "$top.lab70" "roSkillPts" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab71 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Label 
    vTcl:DefineAlias "$top.lab71" "roLvlHealth" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab72 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Stamina 
    vTcl:DefineAlias "$top.lab72" "lblStamina" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent73 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent73" "rwStamina" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab74 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Label 
    vTcl:DefineAlias "$top.lab74" "roStamina" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab75 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Attack 
    vTcl:DefineAlias "$top.lab75" "lblAttack" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab76 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Reflex 
    vTcl:DefineAlias "$top.lab76" "lblReflex" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent77 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent77" "rwAttack" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent78 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$top.ent78" "rwReflex" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab79 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Label 
    vTcl:DefineAlias "$top.lab79" "roAttack" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab80 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Label 
    vTcl:DefineAlias "$top.lab80" "roReflex" vTcl:WidgetProc "Toplevel1" 1
    button $top.but81 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text Close 
    vTcl:DefineAlias "$top.but81" "Close" vTcl:WidgetProc "Toplevel1" 1
    button $top.but82 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text Save 
    vTcl:DefineAlias "$top.but82" "Save" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab43 \
        -in $top -x 10 -y 10 -width 577 -relwidth 0 -height 43 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab44 \
        -in $top -x 20 -y 80 -width 68 -relwidth 0 -height 31 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab45 \
        -in $top -x 100 -y 85 -width 200 -relwidth 0 -height 25 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent47 \
        -in $top -x 100 -y 85 -width 200 -relwidth 0 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.lab48 \
        -in $top -x 40 -y 130 -anchor nw -bordermode ignore 
    place $top.lab49 \
        -in $top -x 110 -y 130 -anchor nw -bordermode ignore 
    place $top.ent50 \
        -in $top -x 110 -y 130 -anchor nw -bordermode ignore 
    place $top.lab51 \
        -in $top -x 30 -y 170 -anchor nw -bordermode ignore 
    place $top.tex52 \
        -in $top -x 110 -y 170 -width 334 -relwidth 0 -height 154 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.lab53 \
        -in $top -x 40 -y 360 -width 74 -relwidth 0 -height 31 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab54 \
        -in $top -x 30 -y 400 -anchor nw -bordermode ignore 
    place $top.lab55 \
        -in $top -x 90 -y 400 -anchor nw -bordermode ignore 
    place $top.ent56 \
        -in $top -x 80 -y 430 -anchor nw -bordermode ignore 
    place $top.lab57 \
        -in $top -x 30 -y 430 -width 26 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab59 \
        -in $top -x 90 -y 430 -width 34 -height 21 -anchor nw \
        -bordermode ignore 
    place $top.ent61 \
        -in $top -x 80 -y 460 -anchor nw -bordermode ignore 
    place $top.lab62 \
        -in $top -x 30 -y 460 -width 26 -height 21 -anchor nw \
        -bordermode ignore 
    place $top.lab63 \
        -in $top -x 90 -y 460 -width 34 -height 21 -anchor nw \
        -bordermode ignore 
    place $top.lab64 \
        -in $top -x 30 -y 490 -width 26 -height 21 -anchor nw \
        -bordermode ignore 
    place $top.lab65 \
        -in $top -x 30 -y 520 -width 26 -height 21 -anchor nw \
        -bordermode ignore 
    place $top.lab66 \
        -in $top -x 30 -y 550 -width 26 -height 21 -anchor nw \
        -bordermode ignore 
    place $top.lab67 \
        -in $top -x 30 -y 580 -width 26 -height 21 -anchor nw \
        -bordermode ignore 
    place $top.ent68 \
        -in $top -x 80 -y 490 -width 164 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.ent69 \
        -in $top -x 80 -y 520 -width 164 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.ent70 \
        -in $top -x 80 -y 550 -width 164 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.ent71 \
        -in $top -x 80 -y 580 -width 164 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.ent43 \
        -in $top -x 80 -y 400 -width 164 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.lab46 \
        -in $top -x 90 -y 490 -width 34 -height 21 -anchor nw \
        -bordermode ignore 
    place $top.lab47 \
        -in $top -x 90 -y 520 -width 34 -height 21 -anchor nw \
        -bordermode ignore 
    place $top.lab50 \
        -in $top -x 90 -y 550 -width 34 -height 21 -anchor nw \
        -bordermode ignore 
    place $top.lab52 \
        -in $top -x 90 -y 580 -width 34 -height 21 -anchor nw \
        -bordermode ignore 
    place $top.lab56 \
        -in $top -x 290 -y 400 -width 26 -height 21 -anchor nw \
        -bordermode ignore 
    place $top.lab58 \
        -in $top -x 280 -y 430 -width 46 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab60 \
        -in $top -x 280 -y 460 -width 46 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab61 \
        -in $top -x 270 -y 490 -width 66 -relwidth 0 -height 21 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent62 \
        -in $top -x 340 -y 400 -width 164 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.ent63 \
        -in $top -x 340 -y 430 -width 164 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.ent64 \
        -in $top -x 340 -y 460 -width 164 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.ent65 \
        -in $top -x 340 -y 490 -width 164 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.lab68 \
        -in $top -x 350 -y 400 -width 34 -height 21 -anchor nw \
        -bordermode ignore 
    place $top.lab69 \
        -in $top -x 350 -y 430 -width 34 -height 21 -anchor nw \
        -bordermode ignore 
    place $top.lab70 \
        -in $top -x 350 -y 460 -width 34 -height 21 -anchor nw \
        -bordermode ignore 
    place $top.lab71 \
        -in $top -x 350 -y 490 -width 34 -height 21 -anchor nw \
        -bordermode ignore 
    place $top.lab72 \
        -in $top -x 270 -y 520 -width 66 -height 21 -anchor nw \
        -bordermode ignore 
    place $top.ent73 \
        -in $top -x 340 -y 520 -width 164 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.lab74 \
        -in $top -x 350 -y 520 -width 34 -height 21 -anchor nw \
        -bordermode ignore 
    place $top.lab75 \
        -in $top -x 270 -y 550 -width 66 -height 21 -anchor nw \
        -bordermode ignore 
    place $top.lab76 \
        -in $top -x 270 -y 580 -width 66 -height 21 -anchor nw \
        -bordermode ignore 
    place $top.ent77 \
        -in $top -x 340 -y 550 -width 164 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.ent78 \
        -in $top -x 340 -y 580 -width 164 -height 20 -anchor nw \
        -bordermode ignore 
    place $top.lab79 \
        -in $top -x 350 -y 550 -width 34 -height 21 -anchor nw \
        -bordermode ignore 
    place $top.lab80 \
        -in $top -x 350 -y 580 -width 34 -height 21 -anchor nw \
        -bordermode ignore 
    place $top.but81 \
        -in $top -x 30 -y 630 -width 127 -relwidth 0 -height 64 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but82 \
        -in $top -x 390 -y 630 -width 127 -height 64 -anchor nw \
        -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

