#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# Support module generated by PAGE version 4.18
#  in conjunction with Tcl version 8.6
#    Nov 25, 2018 01:38:26 PM EST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

import sys, os.path
datapath = os.path.abspath(os.path.join(os.path.dirname(__file__), "../..") + '/OA Data Files')
import app_config

import ArchType

def init(top, gui, *args, **kwargs):
    global w, top_level, root
    w = gui
    top_level = top
    root = top

def destroy_window():
    # Function which closes the window.
    global top_level
    global w

    top_level.destroy()
    w = None

def close_click():
    destroy_window()

def edit_click():
    global w
    global current_archtype
    global rollback_archtype

    rollback_archtype = current_archtype

    enable_form()

    w.left_button.config(text='Cancel')
    w.left_button.configure(command=cancel_click)

    w.right_button.config(text='Save')
    w.right_button.configure(command=save_click)

def cancel_click():
    global w
    global rollback_archtype

    load_data(rollback_archtype)

    disable_form()

    w.left_button.config(text='Close')
    w.left_button.configure(command=close_click)

    w.right_button.config(text='Edit')
    w.right_button.configure(command=edit_click)

def save_click():
    global save_callback
    global current_archtype

    current_archtype.name = w.ename.get()
    current_archtype.shortDescription = w.eshortdescription.get()
    current_archtype.description = w.txtdescription.get("1.0",'end-1c')
    current_archtype.proficiency = w.eproficiency.get()
    current_archtype.strBonus = w.estr.get()
    current_archtype.perBonus = w.eper.get()
    current_archtype.intBonus = w.eint.get()
    current_archtype.dexBonus = w.edex.get()
    current_archtype.chaBonus = w.echa.get()
    current_archtype.vitBonus = w.evit.get()
    current_archtype.magBonus = w.emag.get()
    current_archtype.staminaBonus = w.estamina.get()
    current_archtype.attackBonus = w.eattack.get()
    current_archtype.reflexBonus = w.ereflex.get()
    current_archtype.feats = w.efeats.get()
    current_archtype.movement = w.emvmt.get()
    current_archtype.skillPoints = w.eskillpts.get()
    current_archtype.levelHealth = w.elvlhealth.get()

    save_callback(current_archtype)

    disable_form()

    w.left_button.config(text='Close')
    w.left_button.configure(command=close_click)

    w.right_button.config(text='Edit')
    w.right_button.configure(command=edit_click)

def enable_form():
    global w

    w.ename.config(state='normal')
    w.eshortdescription.config(state='normal')
    w.eproficiency.config(state='normal')
    w.estr.config(state='normal')
    w.eper.config(state='normal')
    w.eint.config(state='normal')
    w.edex.config(state='normal')
    w.echa.config(state='normal')
    w.evit.config(state='normal')
    w.emag.config(state='normal')
    w.estamina.config(state='normal')
    w.eattack.config(state='normal')
    w.ereflex.config(state='normal')
    w.efeats.config(state='normal')
    w.emvmt.config(state='normal')
    w.eskillpts.config(state='normal')
    w.elvlhealth.config(state='normal')

def disable_form():
    global w

    w.ename.config(state='disabled')
    w.eshortdescription.config(state='disabled')
    w.eproficiency.config(state='disabled')
    w.estr.config(state='disabled')
    w.eper.config(state='disabled')
    w.eint.config(state='disabled')
    w.edex.config(state='disabled')
    w.echa.config(state='disabled')
    w.evit.config(state='disabled')
    w.emag.config(state='disabled')
    w.estamina.config(state='disabled')
    w.eattack.config(state='disabled')
    w.ereflex.config(state='disabled')
    w.efeats.config(state='disabled')
    w.emvmt.config(state='disabled')
    w.eskillpts.config(state='disabled')
    w.elvlhealth.config(state='disabled')

def load_form(archtype, callback):
    global save_callback
    global original_archtype

    original_archtype = archtype.clone()

    save_callback = callback

    load_data(archtype)

def load_data(archtype):
    global w
    global top_level
    global current_archtype

    current_archtype = archtype.clone()

    top_level.title("Archtype - " + current_archtype.name)
    w.lbltitle.config(text="Archtype - " + current_archtype.name)

    enable_form()

    w.ename.delete(0, 'end')
    w.ename.insert(0, current_archtype.name)

    w.eshortdescription.delete(0, 'end')
    w.eshortdescription.insert(0, current_archtype.short_description)

    w.txtdescription.delete("1.0",'end')
    w.txtdescription.insert('end',current_archtype.description)

    w.eproficiency.delete(0, 'end')
    w.eproficiency.insert(0, current_archtype.proficiency)

    w.estr.delete(0, 'end')
    w.estr.insert(0, current_archtype.str_bonus)

    w.eper.delete(0, 'end')
    w.eper.insert(0, current_archtype.per_bonus)

    w.eint.delete(0, 'end')
    w.eint.insert(0, current_archtype.int_bonus)

    w.edex.delete(0, 'end')
    w.edex.insert(0, current_archtype.dex_bonus)

    w.echa.delete(0, 'end')
    w.echa.insert(0, current_archtype.cha_bonus)

    w.evit.delete(0, 'end')
    w.evit.insert(0, current_archtype.vit_bonus)

    w.emag.delete(0, 'end')
    w.emag.insert(0, current_archtype.mag_bonus)

    w.estamina.delete(0, 'end')
    w.estamina.insert(0, current_archtype.stamina_bonus)

    w.eattack.delete(0, 'end')
    w.eattack.insert(0, current_archtype.attack_bonus)

    w.ereflex.delete(0, 'end')
    w.ereflex.insert(0, current_archtype.reflex_bonus)

    w.efeats.delete(0, 'end')
    w.efeats.insert(0, current_archtype.feats)

    w.emvmt.delete(0, 'end')
    w.emvmt.insert(0, current_archtype.movement)

    w.eskillpts.delete(0, 'end')
    w.eskillpts.insert(0, current_archtype.skill_points)

    w.elvlhealth.delete(0, 'end')
    w.elvlhealth.insert(0, current_archtype.level_health)

    disable_form()

if __name__ == '__main__':
    import GUI_Archtype.py
    GUI_Archtype.py.vp_start_gui()
