#! /usr/bin/env python
#  -*- coding: utf-8 -*-
#
# GUI module generated by PAGE version 4.18
#  in conjunction with Tcl version 8.6
#    Nov 24, 2018 09:36:38 PM EST  platform: Windows NT

import sys

try:
    import Tkinter as tk
except ImportError:
    import tkinter as tk

try:
    import ttk
    py3 = False
except ImportError:
    import tkinter.ttk as ttk
    py3 = True

import GUI_List_support

def vp_start_gui():
    '''Starting point when module is the main routine.'''
    global val, w, root
    root = tk.Tk()
    GUI_List_support.set_Tk_var()
    top = Toplevel1 (root)
    GUI_List_support.init(root, top)
    root.mainloop()

w = None
def create_root():
    global val, w, root
    root = tk.Tk()
    top = Toplevel1 (root)
    GUI_List_support.init(root, top)
    return (root, top)

def create_toplevel1(root, *args, **kwargs):
    '''Starting point when module is imported by another program.'''
    global w, w_win, rt
    rt = root
    w = tk.Toplevel (root)
    GUI_List_support.set_Tk_var()
    top = Toplevel1 (w)
    GUI_List_support.init(w, top, *args, **kwargs)
    return (w, top)

def build_list(list_type, list_items, editcall):
    global w
    GUI_List_support.build_list(list_type, list_items, editcall)

def destroy_toplevel1():
    global w
    w.destroy()
    w = None

class Toplevel1:
    def __init__(self, top=None):

        font9 = "-family {Segoe UI} -size 20 -weight bold -slant roman"  \
            " -underline 0 -overstrike 0"

        top.geometry("543x616+407+109")
        top.title("LIST NOT LOADED")
        top.configure(background="#d9d9d9")
        top.configure(highlightbackground="#d9d9d9")
        top.configure(highlightcolor="black")

        self.lbltitle = tk.Label(top)
        self.lbltitle.place(relx=0.018, rely=0.032, height=51, width=514)
        self.lbltitle.configure(background="#d9d9d9")
        self.lbltitle.configure(font=font9)
        self.lbltitle.configure(foreground="#000000")
        self.lbltitle.configure(text='''LIST NOT LOADED''')

        self.cancel = tk.Button(top)
        self.cancel.place(relx=0.018, rely=0.893, height=64, width=107)
        self.cancel.configure(activebackground="#d9d9d9")
        self.cancel.configure(activeforeground="#000000")
        self.cancel.configure(background="#d9d9d9")
        self.cancel.configure(command=GUI_List_support.cancel_click)
        self.cancel.configure(disabledforeground="#a3a3a3")
        self.cancel.configure(foreground="#000000")
        self.cancel.configure(highlightbackground="#d9d9d9")
        self.cancel.configure(highlightcolor="black")
        self.cancel.configure(pady="0")
        self.cancel.configure(text='''Cancel''')

if __name__ == '__main__':
    vp_start_gui()
