#############################################################################
# Generated by PAGE version 4.18
#  in conjunction with Tcl version 8.6
#  Nov 20, 2018 09:30:44 PM EST  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #d9d9d9
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #d8d8d8
set vTcl(active_menu_fg) #000000
}

#############################################################################
# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {Segoe UI} -size 14 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font10
vTcl:font:add_font \
    "-family {Segoe UI} -size 13 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font12
vTcl:font:add_font \
    "-family {Segoe UI} -size 16 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font13
vTcl:font:add_font \
    "-family {Segoe UI} -size 22 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font14
vTcl:font:add_font \
    "-family {Courier New} -size 22 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font15
vTcl:font:add_font \
    "-family {Segoe UI} -size 13 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font16
vTcl:font:add_font \
    "-family {Segoe UI} -size 15 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font17
vTcl:font:add_font \
    "-family {Segoe UI} -size 15 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font18
vTcl:font:add_font \
    "-family {Segoe UI} -size 20 -weight bold -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font19
vTcl:font:add_font \
    "-family {Segoe UI} -size 11 -weight normal -slant roman -underline 0 -overstrike 0" \
    user \
    vTcl:font21
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m69" -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 694x742+424+77
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1604 881
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "OA Manager"
    vTcl:DefineAlias "$top" "OAManagerMainWindow" vTcl:Toplevel:WidgetProc "" 1
    frame $top.fra43 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 725 \
        -highlightbackground {#d9d9d9} -highlightcolor black -width 675 
    vTcl:DefineAlias "$top.fra43" "CharacterFrame" vTcl:WidgetProc "OAManagerMainWindow" 1
    set site_3_0 $top.fra43
    label $site_3_0.lab44 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font14,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify right \
        -text {Name: } 
    vTcl:DefineAlias "$site_3_0.lab44" "lblCharacterName" vTcl:WidgetProc "OAManagerMainWindow" 1
    entry $site_3_0.ent45 \
        -background white -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font15,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent45" "rwCharacterName" vTcl:WidgetProc "OAManagerMainWindow" 1
    label $site_3_0.lab46 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font14,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Label 
    vTcl:DefineAlias "$site_3_0.lab46" "roCharacterName" vTcl:WidgetProc "OAManagerMainWindow" 1
    label $site_3_0.lab48 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {Species: } 
    vTcl:DefineAlias "$site_3_0.lab48" "lblCharacterSpecies" vTcl:WidgetProc "OAManagerMainWindow" 1
    label $site_3_0.lab49 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text {Archtype: } 
    vTcl:DefineAlias "$site_3_0.lab49" "lblCharacterArch" vTcl:WidgetProc "OAManagerMainWindow" 1
    label $site_3_0.lab50 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Label 
    vTcl:DefineAlias "$site_3_0.lab50" "roCharacterSpecies" vTcl:WidgetProc "OAManagerMainWindow" 1
    label $site_3_0.lab51 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Label 
    vTcl:DefineAlias "$site_3_0.lab51" "roCharacterArch" vTcl:WidgetProc "OAManagerMainWindow" 1
    ttk::combobox $site_3_0.tCo54 \
        -textvariable combobox -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo54" "pickCharacterArch" vTcl:WidgetProc "OAManagerMainWindow" 1
    ttk::combobox $site_3_0.tCo55 \
        -textvariable combobox -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo55" "pickCharacterArch_5" vTcl:WidgetProc "OAManagerMainWindow" 1
    label $site_3_0.lab57 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text {Age: } 
    vTcl:DefineAlias "$site_3_0.lab57" "lblCharacterAge" vTcl:WidgetProc "OAManagerMainWindow" 1
    label $site_3_0.lab58 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Label 
    vTcl:DefineAlias "$site_3_0.lab58" "roCharacterAge" vTcl:WidgetProc "OAManagerMainWindow" 1
    entry $site_3_0.ent59 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent59" "rwCharacterAge" vTcl:WidgetProc "OAManagerMainWindow" 1
    label $site_3_0.lab60 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text {Size: } 
    vTcl:DefineAlias "$site_3_0.lab60" "lblCharacterSize" vTcl:WidgetProc "OAManagerMainWindow" 1
    entry $site_3_0.ent61 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent61" "rwCharacterSize" vTcl:WidgetProc "OAManagerMainWindow" 1
    label $site_3_0.lab62 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Label 
    vTcl:DefineAlias "$site_3_0.lab62" "roCharacterSize" vTcl:WidgetProc "OAManagerMainWindow" 1
    label $site_3_0.lab63 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text {Level: } 
    vTcl:DefineAlias "$site_3_0.lab63" "lblCharacterLevel" vTcl:WidgetProc "OAManagerMainWindow" 1
    label $site_3_0.lab64 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Label 
    vTcl:DefineAlias "$site_3_0.lab64" "roCharacterLevel" vTcl:WidgetProc "OAManagerMainWindow" 1
    entry $site_3_0.ent65 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black 
    vTcl:DefineAlias "$site_3_0.ent65" "rwCharacterLevel" vTcl:WidgetProc "OAManagerMainWindow" 1
    label $site_3_0.lab66 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -justify right -text {Focus: } 
    vTcl:DefineAlias "$site_3_0.lab66" "lblCharacterFocus" vTcl:WidgetProc "OAManagerMainWindow" 1
    ttk::combobox $site_3_0.tCo67 \
        -textvariable combobox -foreground {} -background {} -takefocus {} 
    vTcl:DefineAlias "$site_3_0.tCo67" "pickCharacterFocus" vTcl:WidgetProc "OAManagerMainWindow" 1
    label $site_3_0.lab68 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Label 
    vTcl:DefineAlias "$site_3_0.lab68" "roCharacterFocus" vTcl:WidgetProc "OAManagerMainWindow" 1
    frame $site_3_0.fra44 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 470 \
        -width 210 
    vTcl:DefineAlias "$site_3_0.fra44" "TraitsFrame" vTcl:WidgetProc "OAManagerMainWindow" 1
    set site_4_0 $site_3_0.fra44
    label $site_4_0.lab46 \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font19,object) -foreground {#000000} \
        -text Traits 
    vTcl:DefineAlias "$site_4_0.lab46" "lblTraitTitle" vTcl:WidgetProc "OAManagerMainWindow" 1
    label $site_4_0.lab47 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font18,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify right \
        -text MAG 
    vTcl:DefineAlias "$site_4_0.lab47" "lblCharacterMAG" vTcl:WidgetProc "OAManagerMainWindow" 1
    label $site_4_0.lab48 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font13,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Primary 
    vTcl:DefineAlias "$site_4_0.lab48" "lblPrimaryTraitsTitle" vTcl:WidgetProc "OAManagerMainWindow" 1
    label $site_4_0.lab49 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font18,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify right \
        -text STR 
    vTcl:DefineAlias "$site_4_0.lab49" "lblCharacterSTR" vTcl:WidgetProc "OAManagerMainWindow" 1
    label $site_4_0.lab50 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font18,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify right \
        -text PER 
    vTcl:DefineAlias "$site_4_0.lab50" "lblCharacterPER" vTcl:WidgetProc "OAManagerMainWindow" 1
    label $site_4_0.lab51 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font18,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify right \
        -text INT 
    vTcl:DefineAlias "$site_4_0.lab51" "lblCharacterINT" vTcl:WidgetProc "OAManagerMainWindow" 1
    label $site_4_0.lab52 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font18,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify right \
        -text DEX 
    vTcl:DefineAlias "$site_4_0.lab52" "lblCharacterDEX" vTcl:WidgetProc "OAManagerMainWindow" 1
    label $site_4_0.lab53 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font18,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify right \
        -text CHA 
    vTcl:DefineAlias "$site_4_0.lab53" "lblCharacterCHA" vTcl:WidgetProc "OAManagerMainWindow" 1
    label $site_4_0.lab54 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font18,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify right \
        -text VIT 
    vTcl:DefineAlias "$site_4_0.lab54" "lblCharacterVIT" vTcl:WidgetProc "OAManagerMainWindow" 1
    label $site_4_0.lab55 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font10,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Secondary 
    vTcl:DefineAlias "$site_4_0.lab55" "lblSecondaryTraitsTitle" vTcl:WidgetProc "OAManagerMainWindow" 1
    label $site_4_0.lab56 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font12,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify right \
        -text HEALTH 
    vTcl:DefineAlias "$site_4_0.lab56" "lblCharacterHealth" vTcl:WidgetProc "OAManagerMainWindow" 1
    label $site_4_0.lab58 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font12,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify right \
        -text STAMINA 
    vTcl:DefineAlias "$site_4_0.lab58" "lblCharacterStamina" vTcl:WidgetProc "OAManagerMainWindow" 1
    label $site_4_0.lab59 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font17,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Label 
    vTcl:DefineAlias "$site_4_0.lab59" "roCharacterSTR" vTcl:WidgetProc "OAManagerMainWindow" 1
    spinbox $site_4_0.spi60 \
        -activebackground {#f9f9f9} -background white \
        -buttonbackground {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font17,object) -foreground black -from 1.0 \
        -highlightbackground black -highlightcolor black -increment 1.0 \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable spinbox -to 100.0 
    vTcl:DefineAlias "$site_4_0.spi60" "spnCharacterSTR" vTcl:WidgetProc "OAManagerMainWindow" 1
    label $site_4_0.lab61 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font17,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Label 
    vTcl:DefineAlias "$site_4_0.lab61" "roCharacterPER" vTcl:WidgetProc "OAManagerMainWindow" 1
    spinbox $site_4_0.spi62 \
        -activebackground {#f9f9f9} -background white \
        -buttonbackground {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font17,object) -foreground black -from 1.0 \
        -highlightbackground black -highlightcolor black -increment 1.0 \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable spinbox -to 100.0 
    vTcl:DefineAlias "$site_4_0.spi62" "spnCharacterPER" vTcl:WidgetProc "OAManagerMainWindow" 1
    label $site_4_0.lab63 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font17,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Label 
    vTcl:DefineAlias "$site_4_0.lab63" "roCharacterINT" vTcl:WidgetProc "OAManagerMainWindow" 1
    spinbox $site_4_0.spi64 \
        -activebackground {#f9f9f9} -background white \
        -buttonbackground {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font17,object) -foreground black -from 1.0 \
        -highlightbackground black -highlightcolor black -increment 1.0 \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable spinbox -to 100.0 
    vTcl:DefineAlias "$site_4_0.spi64" "spnCharacterINT" vTcl:WidgetProc "OAManagerMainWindow" 1
    label $site_4_0.lab65 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font17,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Label 
    vTcl:DefineAlias "$site_4_0.lab65" "roCharacterDEX" vTcl:WidgetProc "OAManagerMainWindow" 1
    spinbox $site_4_0.spi66 \
        -activebackground {#f9f9f9} -background white \
        -buttonbackground {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font17,object) -foreground black -from 1.0 \
        -highlightbackground black -highlightcolor black -increment 1.0 \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable spinbox -to 100.0 
    vTcl:DefineAlias "$site_4_0.spi66" "spnCharacterDEX" vTcl:WidgetProc "OAManagerMainWindow" 1
    label $site_4_0.lab67 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font17,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Label 
    vTcl:DefineAlias "$site_4_0.lab67" "roCharacterCHA" vTcl:WidgetProc "OAManagerMainWindow" 1
    spinbox $site_4_0.spi68 \
        -activebackground {#f9f9f9} -background white \
        -buttonbackground {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font17,object) -foreground black -from 1.0 \
        -highlightbackground black -highlightcolor black -increment 1.0 \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable spinbox -to 100.0 
    vTcl:DefineAlias "$site_4_0.spi68" "spnCharacterCHA" vTcl:WidgetProc "OAManagerMainWindow" 1
    label $site_4_0.lab69 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font17,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Label 
    vTcl:DefineAlias "$site_4_0.lab69" "roCharacterVIT" vTcl:WidgetProc "OAManagerMainWindow" 1
    spinbox $site_4_0.spi70 \
        -activebackground {#f9f9f9} -background white \
        -buttonbackground {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font17,object) -foreground black -from 1.0 \
        -highlightbackground black -highlightcolor black -increment 1.0 \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable spinbox -to 100.0 
    vTcl:DefineAlias "$site_4_0.spi70" "spnCharacterVIT" vTcl:WidgetProc "OAManagerMainWindow" 1
    label $site_4_0.lab71 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font17,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Label 
    vTcl:DefineAlias "$site_4_0.lab71" "roCharacterMAG" vTcl:WidgetProc "OAManagerMainWindow" 1
    spinbox $site_4_0.spi72 \
        -activebackground {#f9f9f9} -background white \
        -buttonbackground {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font17,object) -foreground black -from 1.0 \
        -highlightbackground black -highlightcolor black -increment 1.0 \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -textvariable spinbox -to 100.0 
    vTcl:DefineAlias "$site_4_0.spi72" "spnCharacterMAG" vTcl:WidgetProc "OAManagerMainWindow" 1
    label $site_4_0.lab74 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font12,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify right \
        -text MANA 
    vTcl:DefineAlias "$site_4_0.lab74" "lblCharacterMana" vTcl:WidgetProc "OAManagerMainWindow" 1
    label $site_4_0.lab75 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font16,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Label 
    vTcl:DefineAlias "$site_4_0.lab75" "roCharacterHealth" vTcl:WidgetProc "OAManagerMainWindow" 1
    label $site_4_0.lab76 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font16,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Label 
    vTcl:DefineAlias "$site_4_0.lab76" "roCharacterStamina" vTcl:WidgetProc "OAManagerMainWindow" 1
    label $site_4_0.lab77 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font16,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Label 
    vTcl:DefineAlias "$site_4_0.lab77" "roCharacterMana" vTcl:WidgetProc "OAManagerMainWindow" 1
    label $site_4_0.lab78 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font16,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Label 
    vTcl:DefineAlias "$site_4_0.lab78" "roCharacterPsi" vTcl:WidgetProc "OAManagerMainWindow" 1
    label $site_4_0.lab79 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font12,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify right \
        -text PSI 
    vTcl:DefineAlias "$site_4_0.lab79" "lblCharacterPsi" vTcl:WidgetProc "OAManagerMainWindow" 1
    place $site_4_0.lab46 \
        -in $site_4_0 -x 10 -y 10 -width 190 -relwidth 0 -height 35 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab47 \
        -in $site_4_0 -x 50 -y 270 -width 50 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab48 \
        -in $site_4_0 -x 10 -y 50 -width 190 -relwidth 0 -height 35 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab49 \
        -in $site_4_0 -x 0 -relx 0.238 -y 0 -rely 0.191 -width 50 -relwidth 0 \
        -height 30 -anchor nw -bordermode ignore 
    place $site_4_0.lab50 \
        -in $site_4_0 -x 0 -relx 0.238 -y 0 -rely 0.255 -width 50 -relwidth 0 \
        -height 30 -anchor nw -bordermode ignore 
    place $site_4_0.lab51 \
        -in $site_4_0 -x 0 -relx 0.238 -y 0 -rely 0.319 -width 50 -relwidth 0 \
        -height 30 -anchor nw -bordermode ignore 
    place $site_4_0.lab52 \
        -in $site_4_0 -x 0 -relx 0.238 -y 0 -rely 0.383 -width 50 -relwidth 0 \
        -height 30 -anchor nw -bordermode ignore 
    place $site_4_0.lab53 \
        -in $site_4_0 -x 0 -relx 0.238 -y 0 -rely 0.447 -width 50 -relwidth 0 \
        -height 30 -anchor nw -bordermode ignore 
    place $site_4_0.lab54 \
        -in $site_4_0 -x 50 -y 240 -width 50 -relwidth 0 -height 30 \
        -anchor nw -bordermode ignore 
    place $site_4_0.lab55 \
        -in $site_4_0 -x 10 -y 310 -width 190 -relwidth 0 -height 35 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab56 \
        -in $site_4_0 -x 0 -relx 0.1 -y 0 -rely 0.723 -width 80 -relwidth 0 \
        -height 30 -anchor nw -bordermode ignore 
    place $site_4_0.lab58 \
        -in $site_4_0 -x 0 -relx 0.1 -y 0 -rely 0.787 -width 80 -relwidth 0 \
        -height 30 -anchor nw -bordermode ignore 
    place $site_4_0.lab59 \
        -in $site_4_0 -x 0 -relx 0.571 -y 0 -rely 0.191 -width 40 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.spi60 \
        -in $site_4_0 -x 0 -relx 0.571 -y 0 -rely 0.191 -width 0 \
        -relwidth 0.19 -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab61 \
        -in $site_4_0 -x 0 -relx 0.571 -y 0 -rely 0.255 -width 0 \
        -relwidth 0.19 -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.spi62 \
        -in $site_4_0 -x 0 -relx 0.571 -y 120 -width 0 -relwidth 0.19 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab63 \
        -in $site_4_0 -x 0 -relx 0.571 -y 0 -rely 0.319 -width 40 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.spi64 \
        -in $site_4_0 -x 0 -relx 0.571 -y 0 -rely 0.319 -width 0 \
        -relwidth 0.19 -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab65 \
        -in $site_4_0 -x 0 -relx 0.571 -y 0 -rely 0.383 -width 0 \
        -relwidth 0.19 -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.spi66 \
        -in $site_4_0 -x 0 -relx 0.571 -y 0 -rely 0.383 -width 0 \
        -relwidth 0.19 -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab67 \
        -in $site_4_0 -x 0 -relx 0.571 -y 210 -width 0 -relwidth 0.19 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.spi68 \
        -in $site_4_0 -x 120 -y 210 -width 40 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab69 \
        -in $site_4_0 -x 120 -y 240 -width 40 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.spi70 \
        -in $site_4_0 -x 120 -y 240 -width 40 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab71 \
        -in $site_4_0 -x 0 -relx 0.571 -y 270 -width 40 -relwidth 0 \
        -height 30 -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.spi72 \
        -in $site_4_0 -x 120 -y 270 -width 40 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab74 \
        -in $site_4_0 -x 0 -relx 0.1 -y 0 -rely 0.851 -width 80 -relwidth 0 \
        -height 30 -anchor nw -bordermode ignore 
    place $site_4_0.lab75 \
        -in $site_4_0 -x 110 -y 340 -width 70 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab76 \
        -in $site_4_0 -x 110 -y 370 -width 70 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab77 \
        -in $site_4_0 -x 110 -y 400 -width 70 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab78 \
        -in $site_4_0 -x 110 -y 430 -width 70 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab79 \
        -in $site_4_0 -x 0 -relx 0.1 -y 0 -rely 0.915 -width 80 -relwidth 0 \
        -height 30 -anchor nw -bordermode ignore 
    frame $site_3_0.fra80 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 225 \
        -width 215 
    vTcl:DefineAlias "$site_3_0.fra80" "FeatsFrame" vTcl:WidgetProc "OAManagerMainWindow" 1
    set site_4_0 $site_3_0.fra80
    text $site_4_0.tex81 \
        -background white -font TkTextFont -foreground black -height 164 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -width 184 -wrap word 
    .top42.fra43.fra80.tex81 configure -font TkTextFont
    .top42.fra43.fra80.tex81 insert end text
    vTcl:DefineAlias "$site_4_0.tex81" "roCharacterFeats" vTcl:WidgetProc "OAManagerMainWindow" 1
    label $site_4_0.lab82 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font13,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Feats 
    vTcl:DefineAlias "$site_4_0.lab82" "lblFeatsTitle" vTcl:WidgetProc "OAManagerMainWindow" 1
    place $site_4_0.tex81 \
        -in $site_4_0 -x 10 -y 50 -width 195 -relwidth 0 -height 164 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab82 \
        -in $site_4_0 -x 10 -y 10 -width 195 -relwidth 0 -height 25 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $site_3_0.fra85 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 225 \
        -width 215 
    vTcl:DefineAlias "$site_3_0.fra85" "SkillFrame" vTcl:WidgetProc "OAManagerMainWindow" 1
    set site_4_0 $site_3_0.fra85
    text $site_4_0.tex86 \
        -background white -font TkTextFont -foreground black -height 164 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -takefocus 0 -width 234 -wrap word 
    .top42.fra43.fra85.tex86 configure -font TkTextFont
    .top42.fra43.fra85.tex86 insert end text
    vTcl:DefineAlias "$site_4_0.tex86" "roCharacterSkills" vTcl:WidgetProc "OAManagerMainWindow" 1
    label $site_4_0.lab87 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font13,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Skills 
    vTcl:DefineAlias "$site_4_0.lab87" "lblFeatsTitle_15" vTcl:WidgetProc "OAManagerMainWindow" 1
    place $site_4_0.tex86 \
        -in $site_4_0 -x 10 -y 50 -width 195 -relwidth 0 -height 164 \
        -anchor nw -bordermode ignore 
    place $site_4_0.lab87 \
        -in $site_4_0 -x 10 -y 10 -width 180 -relwidth 0 -height 25 \
        -anchor nw -bordermode ignore 
    frame $site_3_0.fra89 \
        -borderwidth 2 -relief groove -background {#d9d9d9} -height 245 \
        -width 435 
    vTcl:DefineAlias "$site_3_0.fra89" "EquipmentFrame" vTcl:WidgetProc "OAManagerMainWindow" 1
    set site_4_0 $site_3_0.fra89
    label $site_4_0.lab90 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font13,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -text Equipment 
    vTcl:DefineAlias "$site_4_0.lab90" "lblEquipmentTitle" vTcl:WidgetProc "OAManagerMainWindow" 1
    text $site_4_0.tex91 \
        -background white -font TkTextFont -foreground black -height 164 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -takefocus 0 -width 195 -wrap word 
    .top42.fra43.fra89.tex91 configure -font TkTextFont
    .top42.fra43.fra89.tex91 insert end text
    vTcl:DefineAlias "$site_4_0.tex91" "roCharacterEquipment1" vTcl:WidgetProc "OAManagerMainWindow" 1
    text $site_4_0.tex92 \
        -background white -font TkTextFont -foreground black -height 44 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -takefocus 0 -width 195 -wrap word 
    .top42.fra43.fra89.tex92 configure -font TkTextFont
    .top42.fra43.fra89.tex92 insert end text
    vTcl:DefineAlias "$site_4_0.tex92" "roCharacterArmor" vTcl:WidgetProc "OAManagerMainWindow" 1
    label $site_4_0.lab93 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font21,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify right \
        -text Money 
    vTcl:DefineAlias "$site_4_0.lab93" "lblCharacterMoney" vTcl:WidgetProc "OAManagerMainWindow" 1
    label $site_4_0.lab94 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text Label 
    vTcl:DefineAlias "$site_4_0.lab94" "roCharacterMoney" vTcl:WidgetProc "OAManagerMainWindow" 1
    entry $site_4_0.ent95 \
        -background white -disabledforeground {#a3a3a3} -font TkFixedFont \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -insertbackground black \
        -selectbackground {#c4c4c4} -selectforeground black -takefocus 0 
    vTcl:DefineAlias "$site_4_0.ent95" "rwCharacterMoney" vTcl:WidgetProc "OAManagerMainWindow" 1
    label $site_4_0.lab96 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font21,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify right \
        -text Armor 
    vTcl:DefineAlias "$site_4_0.lab96" "lblCharacterArmor" vTcl:WidgetProc "OAManagerMainWindow" 1
    text $site_4_0.tex97 \
        -background white -font TkTextFont -foreground black -height 84 \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -insertbackground black -selectbackground {#c4c4c4} \
        -selectforeground black -takefocus 0 -width 195 -wrap word 
    .top42.fra43.fra89.tex97 configure -font TkTextFont
    .top42.fra43.fra89.tex97 insert end text
    vTcl:DefineAlias "$site_4_0.tex97" "roCharacterWeapons" vTcl:WidgetProc "OAManagerMainWindow" 1
    label $site_4_0.lab98 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font21,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify right \
        -text Weapons 
    vTcl:DefineAlias "$site_4_0.lab98" "lblCharacterWeapons" vTcl:WidgetProc "OAManagerMainWindow" 1
    label $site_4_0.lab99 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -font $::vTcl(fonts,vTcl:font21,object) -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black -justify right \
        -text Misc 
    vTcl:DefineAlias "$site_4_0.lab99" "lblCharacterMiscEquip" vTcl:WidgetProc "OAManagerMainWindow" 1
    place $site_4_0.lab90 \
        -in $site_4_0 -x 10 -y 10 -width 195 -height 25 -anchor nw \
        -bordermode ignore 
    place $site_4_0.tex91 \
        -in $site_4_0 -x 230 -y 70 -width 195 -relwidth 0 -height 164 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.tex92 \
        -in $site_4_0 -x 10 -y 70 -width 195 -relwidth 0 -height 44 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab93 \
        -in $site_4_0 -x 230 -y 10 -width 70 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab94 \
        -in $site_4_0 -x 320 -y 10 -width 75 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.ent95 \
        -in $site_4_0 -x 320 -y 12 -width 75 -relwidth 0 -height 30 \
        -anchor nw -bordermode ignore 
    place $site_4_0.lab96 \
        -in $site_4_0 -x 10 -y 50 -width 70 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.tex97 \
        -in $site_4_0 -x 10 -y 150 -width 195 -relwidth 0 -height 84 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab98 \
        -in $site_4_0 -x 10 -y 130 -width 70 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_4_0.lab99 \
        -in $site_4_0 -x 230 -y 50 -width 70 -relwidth 0 -height 20 \
        -relheight 0 -anchor nw -bordermode ignore 
    button $site_3_0.but100 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -takefocus 0 -text Edit 
    vTcl:DefineAlias "$site_3_0.but100" "Edit" vTcl:WidgetProc "OAManagerMainWindow" 1
    button $site_3_0.but101 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -takefocus 0 -text Save 
    vTcl:DefineAlias "$site_3_0.but101" "Save" vTcl:WidgetProc "OAManagerMainWindow" 1
    button $site_3_0.but102 \
        -activebackground {#d9d9d9} -activeforeground {#000000} \
        -background {#d9d9d9} -disabledforeground {#a3a3a3} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -takefocus 0 -text Cancel 
    vTcl:DefineAlias "$site_3_0.but102" "Cancel" vTcl:WidgetProc "OAManagerMainWindow" 1
    place $site_3_0.lab44 \
        -in $site_3_0 -x 40 -y 20 -width 95 -relwidth 0 -height 50 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.ent45 \
        -in $site_3_0 -x 150 -y 20 -width 505 -relwidth 0 -height 50 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab46 \
        -in $site_3_0 -x 150 -y 20 -width 505 -relwidth 0 -height 50 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab48 \
        -in $site_3_0 -x 10 -y 90 -width 75 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab49 \
        -in $site_3_0 -x 350 -y 90 -width 75 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab50 \
        -in $site_3_0 -x 80 -y 90 -width 225 -height 30 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab51 \
        -in $site_3_0 -x 430 -y 90 -width 225 -height 30 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tCo54 \
        -in $site_3_0 -x 430 -y 90 -width 225 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.tCo55 \
        -in $site_3_0 -x 80 -y 90 -width 225 -height 30 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab57 \
        -in $site_3_0 -x 10 -y 120 -width 75 -height 30 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab58 \
        -in $site_3_0 -x 80 -y 120 -width 225 -height 30 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent59 \
        -in $site_3_0 -x 80 -y 120 -width 225 -relwidth 0 -height 30 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab60 \
        -in $site_3_0 -x 10 -y 150 -width 75 -height 30 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent61 \
        -in $site_3_0 -x 80 -y 150 -width 225 -height 30 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab62 \
        -in $site_3_0 -x 80 -y 150 -width 225 -height 30 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab63 \
        -in $site_3_0 -x 350 -y 150 -width 75 -height 30 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab64 \
        -in $site_3_0 -x 430 -y 150 -width 225 -height 30 -anchor nw \
        -bordermode ignore 
    place $site_3_0.ent65 \
        -in $site_3_0 -x 430 -relx 0.637 -y 110 -width 225 -height 30 \
        -anchor nw -bordermode ignore 
    place $site_3_0.lab66 \
        -in $site_3_0 -x 350 -y 120 -width 75 -height 30 -anchor nw \
        -bordermode ignore 
    place $site_3_0.tCo67 \
        -in $site_3_0 -x 430 -y 120 -width 225 -height 30 -anchor nw \
        -bordermode ignore 
    place $site_3_0.lab68 \
        -in $site_3_0 -x 0 -relx 0.637 -y 120 -width 225 -height 30 \
        -anchor nw -bordermode ignore 
    place $site_3_0.fra44 \
        -in $site_3_0 -x 10 -y 190 -width 210 -relwidth 0 -height 470 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.fra80 \
        -in $site_3_0 -x 230 -y 190 -width 215 -relwidth 0 -height 225 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.fra85 \
        -in $site_3_0 -x 450 -y 190 -width 215 -relwidth 0 -height 225 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.fra89 \
        -in $site_3_0 -x 230 -y 420 -width 435 -relwidth 0 -height 245 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but100 \
        -in $site_3_0 -x 140 -y 680 -width 57 -relwidth 0 -height 34 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but101 \
        -in $site_3_0 -x 300 -y 680 -width 57 -height 34 -anchor nw \
        -bordermode ignore 
    place $site_3_0.but102 \
        -in $site_3_0 -x 460 -y 680 -width 57 -height 34 -anchor nw \
        -bordermode ignore 
    set site_3_0 $top.m69
    menu $site_3_0 \
        -activebackground {#d8d8d8} -activeforeground {#000000} \
        -background {#d9d9d9} -font TkMenuFont -foreground {#000000} \
        -tearoff 0 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra43 \
        -in $top -x 10 -y 10 -width 675 -relwidth 0 -height 725 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

#############################################################################
## Binding tag:  _TopLevel

bind "_TopLevel" <<Create>> {
    if {![info exists _topcount]} {set _topcount 0}; incr _topcount
}
bind "_TopLevel" <<DeleteWindow>> {
    if {[set ::%W::_modal]} {
                vTcl:Toplevel:WidgetProc %W endmodal
            } else {
                destroy %W; if {$_topcount == 0} {exit}
            }
}
bind "_TopLevel" <Destroy> {
    if {[winfo toplevel %W] == "%W"} {incr _topcount -1}
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

